### PR TITLE
Multi-arch build

### PR DESCRIPTION
**Pull request by imikushin**
Build for arm or amd64 by running `dapper` against a docker host on the target architecture.

### CODE REVIEW

**Comment by imikushin** [comment]
rancher/rancher#4703

**Comment by imikushin** [comment]
@ibuildthecloud  Honestly, don't know what's wrong with the tests

**Comment by cjellick** [comment]
@imikushin looks like the test script is running through all the vendor dirs. can you fix?
```
PASS
ok  	github.com/rancher/host-api/stats	11.494s
?   	github.com/rancher/host-api/testutils	[no test files]
?   	github.com/rancher/host-api/util	[no test files]
?   	github.com/rancher/host-api/vendor/github.com/Sirupsen/logrus	[no test files]
?   	github.com/rancher/host-api/vendor/github.com/dgrijalva/jwt-go	[no test files]
?   	github.com/rancher/host-api/vendor/github.com/docker/docker/opts	[no test files]
?   	github.com/rancher/host-api/vendor/github.com/docker/docker/pkg/archive	[no test files]
?   	github.com/rancher/host-api/vendor/github.com/docker/docker/pkg/fileutils	[no test fil
...
```

**Comment by ibuildthecloud** [comment]
@imikushin I squashed and carried this PR in https://github.com/rancher/host-api/pull/83 so I could fix up the deps

**Pull request closed without merging**
