### PR TITLE
Replaing cadvisor with sigar for getting total system memory

### PR DESCRIPTION
**Pull request by usmanismail**

### CODE REVIEW

**Comment by usmanismail** [comment]
@cjellick First tiny change in replacing CAdvisor. Are you ok with using Sigar?

**Comment by cjellick** [comment]
Replied to your email as well, but yes, check in everything changed under _workspace.
Welcome to the world golang dependencies!

**Comment by ibuildthecloud** [comment]
Can you give a bit more context to why this change is needed.

**Comment by usmanismail** [comment]
@ibuildthecloud 
The larger task is to use Docker Stats API instead of CAdvisor to collect monitoring information about the docker containers. The data can then be fed into a InfluxDB and presented by Graphana. The Stats API does not have host memory and CPU information hence I want to use sigar. We can continue to use CAdvisor for host information but that seems like a heavy weight solution for the a simple use case.

**Comment by cloudnautique** [comment]
We get this from  python-agent already, but I know we are moving to host-api(Go).

**Comment by cjellick** [comment]
Seems like this is going to happen at this point. Going to close it.

**Pull request closed without merging**
