### PR TITLE
Net fix

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/6588

**Comment by StrongMonkey** [comment]
also fixed panic issues.

**Comment by cjellick** [comment]
@StrongMonkey did @ibuildthecloud suggest/approve of using these libs for getting network stats?

**Comment by StrongMonkey** [comment]
@cjellick in managed network we set net:none to container and that caused `docker stats` can not get network stats from that container. @ibuildthecloud suggested using other way to get stats and it is my idea to use netlink to get it.

**Comment by cjellick** [comment]
@StrongMonkey need to rebase

**Comment by StrongMonkey** [comment]
@cjellick rebased

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
